// --- 1. ESTADO GLOBAL ---
let texturaActual = ''; 
let modoEdicion = 'piso'; 

// --- 2. CATÁLOGO COMPLETO POR MARCAS ---
const misProductos = [
    // NITROPISO
    { nombre: "acatlan-30x60", marca: "nitropiso" },
    { nombre: "alameda-60x60", marca: "nitropiso" },
    { nombre: "alhambra-gris-44x44", marca: "nitropiso" },
    { nombre: "alhambra-rojo-44x44", marca: "nitropiso" },
    { nombre: "altamira-33x33", marca: "nitropiso" },
    { nombre: "antigua-44x44", marca: "nitropiso" },
    { nombre: "aquismon-33x33", marca: "nitropiso" },
    { nombre: "arce-azul-19.5x89.5", marca: "nitropiso" },
    { nombre: "arce-azul-30x60", marca: "nitropiso" },
    { nombre: "arce-azul-60x60", marca: "nitropiso" },
    { nombre: "arce-blanco-19.5x89.5", marca: "nitropiso" },
    { nombre: "arce-blanco-30x60", marca: "nitropiso" },
    { nombre: "arce-blanco-60x60", marca: "nitropiso" },
    { nombre: "arce-cafe-19.5x89.5", marca: "nitropiso" },
    { nombre: "arce-cafe-30x60", marca: "nitropiso" },
    { nombre: "arce-cafe-60x60", marca: "nitropiso" },
    { nombre: "arezzo-beige-30x60", marca: "nitropiso" },
    { nombre: "arezzo-blanco-30x60", marca: "nitropiso" },
    { nombre: "arezzo-gris-30x60", marca: "nitropiso" },
    { nombre: "aspen-blanco-30x60", marca: "nitropiso" },
    { nombre: "aspen-rojo-30x60", marca: "nitropiso" },
    { nombre: "bremen-beige-30x60", marca: "nitropiso" },
    { nombre: "bremen-gris-30x60", marca: "nitropiso" },
    { nombre: "brest-30x60", marca: "nitropiso" },
    { nombre: "brookline-60x60", marca: "nitropiso" },
    { nombre: "bursera-gris-20x60", marca: "nitropiso" },
    { nombre: "cadiz-30x60", marca: "nitropiso" },
    { nombre: "calacatta-30x60", marca: "nitropiso" },
    { nombre: "cantera-cafe-30x60", marca: "nitropiso" },
    { nombre: "cantera-negro-30x60", marca: "nitropiso" },
    { nombre: "carrara-blanco-30x60", marca: "nitropiso" },
    { nombre: "carrara-blanco-60x60", marca: "nitropiso" },
    { nombre: "casa-blanca-60x60", marca: "nitropiso" },
    { nombre: "castellon-44x44", marca: "nitropiso" },
    { nombre: "cedral-beige-33x33", marca: "nitropiso" },
    { nombre: "coban-44x44", marca: "nitropiso" },
    { nombre: "concrete-gris-30x60", marca: "nitropiso" },
    { nombre: "copacabana-blanco-30x60", marca: "nitropiso" },
    { nombre: "copacabana-gris-30x60", marca: "nitropiso" },
    { nombre: "cuzco-blanco-50x50", marca: "nitropiso" },
    { nombre: "cuzco-rojo-50x50", marca: "nitropiso" },
    { nombre: "diamante-blanco-30x60", marca: "nitropiso" },
    { nombre: "elegance-nieve-33x33", marca: "nitropiso" },
    { nombre: "grecia-30x60", marca: "nitropiso" },
    { nombre: "greytech-30x60", marca: "nitropiso" },
    { nombre: "hita-beige-59.5x59.5", marca: "nitropiso" },
    { nombre: "hita-blanco-59.5x59.5", marca: "nitropiso" },
    { nombre: "hita-gris-59.5x59.5", marca: "nitropiso" },
    { nombre: "huizache-cognac-33x33", marca: "nitropiso" },
    { nombre: "iguazu-miel-20x60", marca: "nitropiso" },
    { nombre: "iguazu-cafe-20x60", marca: "nitropiso" },
    { nombre: "ipina-45x90", marca: "nitropiso" },
    { nombre: "liverpool-44x44", marca: "nitropiso" },
    { nombre: "loreto-beige-50x50", marca: "nitropiso" },
    { nombre: "lublin-blanco-30x60", marca: "nitropiso" },
    { nombre: "lublin-rojo-30x60", marca: "nitropiso" },
    { nombre: "magna-60x60", marca: "nitropiso" },
    { nombre: "manchester-caoba-60x60", marca: "nitropiso" },
    { nombre: "manchester-chocolate-60x60", marca: "nitropiso" },
    { nombre: "marruecos-gris-30x60", marca: "nitropiso" },
    { nombre: "marruecos-rojo-30x60", marca: "nitropiso" },
    { nombre: "mazzaro-chocolate-20x60", marca: "nitropiso" },
    { nombre: "messel-30x60", marca: "nitropiso" },
    { nombre: "miranda-60x60", marca: "nitropiso" },
    { nombre: "monaco-rojo-30x60", marca: "nitropiso" },
    { nombre: "montecarlo-59.5x59.5", marca: "nitropiso" },
    { nombre: "mosset-30x60", marca: "nitropiso" },
    { nombre: "neiva-60x60", marca: "nitropiso" },
    { nombre: "olmo-rojo-20x60", marca: "nitropiso" },
    { nombre: "onice-beige-44x44", marca: "nitropiso" },
    { nombre: "parma-noce-44x44", marca: "nitropiso" },
    { nombre: "petra-beige-30x60", marca: "nitropiso" },
    { nombre: "petra-gris-30x60", marca: "nitropiso" },
    { nombre: "piedra-de-bernal-44x44", marca: "nitropiso" },
    { nombre: "piedra-de-rio-44x44", marca: "nitropiso" },
    { nombre: "piedra-porfirio-beige-44x44", marca: "nitropiso" },
    { nombre: "piedra-porfirio-rojo-44x44", marca: "nitropiso" },
    { nombre: "porto-30x60", marca: "nitropiso" },
    { nombre: "prado-gris-30x60", marca: "nitropiso" },
    { nombre: "prisma-beige-30x60", marca: "nitropiso" },
    { nombre: "prisma-beige-60x60", marca: "nitropiso" },
    { nombre: "prisma-gris-60x60", marca: "nitropiso" },
    { nombre: "prisma-negro-60x60", marca: "nitropiso" },
    { nombre: "quartz-gris-60x60", marca: "nitropiso" },
    { nombre: "quartz-negro-60x60", marca: "nitropiso" },
    { nombre: "rivalta-cafe-20x60", marca: "nitropiso" },
    { nombre: "rock-clover-negro-60x60", marca: "nitropiso" },
    { nombre: "rock-clover-gris-60x60", marca: "nitropiso" },
    { nombre: "san-diego-50x50", marca: "nitropiso" },
    { nombre: "shangai-33x33", marca: "nitropiso" },
    { nombre: "sherezada-30x60", marca: "nitropiso" },
    { nombre: "steel-20x60", marca: "nitropiso" },
    { nombre: "steel-60x60", marca: "nitropiso" },
    { nombre: "steel-plate-60x60", marca: "nitropiso" },
    { nombre: "tamesi-beige-30x60", marca: "nitropiso" },
    { nombre: "tamesi-negro-30x60", marca: "nitropiso" },
    { nombre: "tamesi-rojo-30x60", marca: "nitropiso" },
    { nombre: "tamuin-beige-33x33", marca: "nitropiso" },
    { nombre: "tamuin-gris-33x33", marca: "nitropiso" },
    { nombre: "torino-60x60", marca: "nitropiso" },
    { nombre: "toulon-20x60", marca: "nitropiso" },
    { nombre: "tuxtla-44x44", marca: "nitropiso" },
    { nombre: "vancouver-blanco-60x60", marca: "nitropiso" },
    { nombre: "zacapa-44x44", marca: "nitropiso" },
    { nombre: "zurich-20x60", marca: "nitropiso" },
    // PORCELANITE
    { nombre: "alabaster-55x55", marca: "porcelanite" },
    { nombre: "andes-plus-blanco-20x30", marca: "porcelanite" },
    { nombre: "aramis-coral-20x30", marca: "porcelanite" },
    { nombre: "aramis-esmeralda-20x30", marca: "porcelanite" },
    { nombre: "aramis-perla-20x30", marca: "porcelanite" },
    { nombre: "aramis-verde-20x30", marca: "porcelanite" },
    { nombre: "aruba-beige-55x55", marca: "porcelanite" },
    { nombre: "asturias-cafe-claro-20x30", marca: "porcelanite" },
    { nombre: "asturias-cafe-oscuro-20x30", marca: "porcelanite" },
    { nombre: "avalon-cafe-55x55", marca: "porcelanite" },
    { nombre: "balmor-blanco-60x60", marca: "porcelanite" },
    { nombre: "belice-blanco-20x30", marca: "porcelanite" },
    { nombre: "belite-gris-44x44", marca: "porcelanite" },
    { nombre: "belite-rojo-44x44", marca: "porcelanite" },
    { nombre: "beta-beige-20x30", marca: "porcelanite" },
    { nombre: "beta-salmon-20x30", marca: "porcelanite" },
    { nombre: "bluette-azul-55x55", marca: "porcelanite" },
    { nombre: "bossa-blanco-20x30", marca: "porcelanite" },
    { nombre: "bossa-blanco-36x36", marca: "porcelanite" },
    { nombre: "boston-beige-20x30", marca: "porcelanite" },
    { nombre: "boston-blanco-20x30", marca: "porcelanite" },
    { nombre: "brada-mix-33x33", marca: "porcelanite" },
    { nombre: "bramassole-bone-30x60", marca: "porcelanite" },
    { nombre: "briko-blanco-20x30", marca: "porcelanite" },
    { nombre: "briko-marble-blanco-20x30", marca: "porcelanite" },
    { nombre: "briko-stone-greige-20x30", marca: "porcelanite" },
    { nombre: "cabos-azul-20x20", marca: "porcelanite" },
    { nombre: "cabos-beige-20x20", marca: "porcelanite" },
    { nombre: "cabos-blanco-20x20", marca: "porcelanite" },
    { nombre: "cantia-blanco-36x36", marca: "porcelanite" },
    { nombre: "cantia-gris-36x36", marca: "porcelanite" },
    { nombre: "carson-gris-25x40", marca: "porcelanite" },
    { nombre: "carson-gris-44x44", marca: "porcelanite" },
    { nombre: "carson-oxford-25x40", marca: "porcelanite" },
    { nombre: "carson-oxford-44x44", marca: "porcelanite" },
    { nombre: "cassalotti-brillante-44x44", marca: "porcelanite" },
    { nombre: "cassalotti-mate-44x44", marca: "porcelanite" },
    { nombre: "creel-glossy-blanco-30x60", marca: "porcelanite" },
    { nombre: "croce-cafe-33x33", marca: "porcelanite" },
    { nombre: "croce-rojo-33x33", marca: "porcelanite" },
    { nombre: "damasco-blanco-55x55", marca: "porcelanite" },
    { nombre: "damasco-crema-55x55", marca: "porcelanite" },
    { nombre: "damasco-gris-55x55", marca: "porcelanite" },
    { nombre: "dent-greka-mix-30x45", marca: "porcelanite" },
    { nombre: "dione-blanco-55x55", marca: "porcelanite" },
    { nombre: "doppio-arena-30x60", marca: "porcelanite" },
    { nombre: "dovela-gris-20x30", marca: "porcelanite" },
    { nombre: "farbe-blanco-25x40", marca: "porcelanite" },
    { nombre: "farbe-negro-25x40", marca: "porcelanite" },
    { nombre: "farbe-rojo-25x40", marca: "porcelanite" },
    { nombre: "fashion-negro-20x30", marca: "porcelanite" },
    { nombre: "fashion-perla-20x30", marca: "porcelanite" },
    { nombre: "florina-azul-44x44", marca: "porcelanite" },
    { nombre: "florina-marron-44x44", marca: "porcelanite" },
    { nombre: "galana-cafe-44x44", marca: "porcelanite" },
    { nombre: "gales-azul-20x30", marca: "porcelanite" },
    { nombre: "gales-beige-20x30", marca: "porcelanite" },
    { nombre: "gales-beige-36x36", marca: "porcelanite" },
    { nombre: "gales-gris-20x30", marca: "porcelanite" },
    { nombre: "gales-gris-36x36", marca: "porcelanite" },
    { nombre: "garda-gris-30x45", marca: "porcelanite" },
    { nombre: "garea-blanco-36x36", marca: "porcelanite" },
    { nombre: "garea-grafito-36x36", marca: "porcelanite" },
    { nombre: "garea-gris-36x36", marca: "porcelanite" },
    { nombre: "harper-blanco-60x1.20", marca: "porcelanite" },
    { nombre: "holbein-black-60x60", marca: "porcelanite" },
    { nombre: "holbein-bone-60x60", marca: "porcelanite" },
    { nombre: "jasper-beige-33x33", marca: "porcelanite" },
    { nombre: "jasper-cafe-33x33", marca: "porcelanite" },
    { nombre: "jasper-carrara-white-33x33", marca: "porcelanite" },
    { nombre: "jasper-grafito-33x33", marca: "porcelanite" },
    { nombre: "kasha-beige-55x55", marca: "porcelanite" },
    { nombre: "kasha-cafe-55x55", marca: "porcelanite" },
    { nombre: "kasha-gris-55x55", marca: "porcelanite" },
    { nombre: "kindsley-bone-59.3x117", marca: "porcelanite" },
    { nombre: "kuo-rosa-20x20", marca: "porcelanite" },
    { nombre: "lauret-hueso-36x36", marca: "porcelanite" },
    { nombre: "leia-blanco-60x60", marca: "porcelanite" },
    { nombre: "ligne-azul-25x40", marca: "porcelanite" },
    { nombre: "ligne-blanco-25x40", marca: "porcelanite" },
    { nombre: "lisva-beige-36x36", marca: "porcelanite" },
    { nombre: "macei-cobalto-30x60", marca: "porcelanite" },
    { nombre: "macei-jade-30x60", marca: "porcelanite" },
    { nombre: "macei-perla-30x60", marca: "porcelanite" },
    { nombre: "madera-bois-cafe-55x55", marca: "porcelanite" },
    { nombre: "madera-diniza-33x33", marca: "porcelanite" },
    { nombre: "madera-girona-55x55", marca: "porcelanite" },
    { nombre: "madera-jaipur-natura-33x33", marca: "porcelanite" },
    { nombre: "madera-tanami-gris-55x55", marca: "porcelanite" },
    { nombre: "madera-tanami-natural-55x55", marca: "porcelanite" },
    { nombre: "madera-tribe-cerezo-18x55", marca: "porcelanite" },
    { nombre: "madera-tribe-gris-18x55", marca: "porcelanite" },
    { nombre: "mahogany-abedul-18x55", marca: "porcelanite" },
    { nombre: "mahogany-fresno-18x55", marca: "porcelanite" },
    { nombre: "mahogany-roble-18x55", marca: "porcelanite" },
    { nombre: "mare-beige-25x40", marca: "porcelanite" },
    { nombre: "malaya-cafe-33x33", marca: "porcelanite" },
    { nombre: "marmol-caselli-44x44", marca: "porcelanite" },
    { nombre: "marmol-casole-44x44", marca: "porcelanite" },
    { nombre: "maroma-rojo-55x55", marca: "porcelanite" },
    { nombre: "marsella-cafe-20x30", marca: "porcelanite" },
    { nombre: "marsella-chocolate-20x30", marca: "porcelanite" },
    { nombre: "messier-deco-blanco-55x55", marca: "porcelanite" },
    { nombre: "mezzo-mix-44x44", marca: "porcelanite" },
    { nombre: "monvile-beige-60x60", marca: "porcelanite" },
    { nombre: "monvile-grafito-60x60", marca: "porcelanite" },
    { nombre: "munet-azul-60x1.20", marca: "porcelanite" },
    { nombre: "mystone-cafe-36x36", marca: "porcelanite" },
    { nombre: "nagara-gris-30x60", marca: "porcelanite" },
    { nombre: "nagara-beige-30x60", marca: "porcelanite" },
    { nombre: "naica-pul-silver-59.3x119", marca: "porcelanite" },
    { nombre: "napoles-beige-55x55", marca: "porcelanite" },
    { nombre: "naturawood-caoba-18x55", marca: "porcelanite" },
    { nombre: "naturawood-natura-18x55", marca: "porcelanite" },
    { nombre: "naturawood-natura-brillante-18x55", marca: "porcelanite" },
    { nombre: "nevada-blanco-brillante-2da-25x40", marca: "porcelanite" },
    { nombre: "nival-blanco-20x30", marca: "porcelanite" },
    { nombre: "nival-carrara-white-20x20", marca: "porcelanite" },
    { nombre: "nival-oxford-20x20", marca: "porcelanite" },
    { nombre: "nobu-cerezo-36x36", marca: "porcelanite" },
    { nombre: "noe-patio-grafito-44x44", marca: "porcelanite" },
    { nombre: "nolan-blanco-25x40", marca: "porcelanite" },
    { nombre: "nolan-deco-blanco-25x40", marca: "porcelanite" },
    { nombre: "paduk-cerezo-44x44", marca: "porcelanite" },
    { nombre: "palco-gris-55x55", marca: "porcelanite" },
    { nombre: "parma-beige-55x55", marca: "porcelanite" },
    { nombre: "pecan-cafe-36x36", marca: "porcelanite" },
    { nombre: "pecan-rojo-36x36", marca: "porcelanite" },
    { nombre: "piombo-brick-marron-36x36", marca: "porcelanite" },
    { nombre: "piombo-marron-20x30", marca: "porcelanite" },
    { nombre: "pompei-beige-25x40", marca: "porcelanite" },
    { nombre: "sain-blanco-30x60", marca: "porcelanite" },
    { nombre: "spazio-blanco-44x44", marca: "porcelanite" },
    { nombre: "spazio-negro-44x44", marca: "porcelanite" },
    { nombre: "san-cristobal-cafe-33x33", marca: "porcelanite" },
    { nombre: "stones-multicolor-20x20", marca: "porcelanite" },
    { nombre: "stones-multicolor-44x44", marca: "porcelanite" },
    { nombre: "sudden-blanco-60x60", marca: "porcelanite" },
    { nombre: "sundeck-haya-18x55", marca: "porcelanite" },
    { nombre: "sunset-azul-33x33", marca: "porcelanite" },
    { nombre: "sunset-beige-33x33", marca: "porcelanite" },
    { nombre: "sunset-verde-33x33", marca: "porcelanite" },
    { nombre: "tabarca-mix-60x60", marca: "porcelanite" },
    { nombre: "tarasco-rojo-33x33", marca: "porcelanite" },
    { nombre: "teak-azul-20x30", marca: "porcelanite" },
    { nombre: "teak-blanco-20x30", marca: "porcelanite" },
    { nombre: "timberwood-cafe-18x55", marca: "porcelanite" },
    { nombre: "tribe-glossy-gris-18x55", marca: "porcelanite" },
    { nombre: "tribe-glossy-natura-18x55", marca: "porcelanite" },
    { nombre: "tribe-glossy-cerezo-18x55", marca: "porcelanite" },
    { nombre: "venecia-azul-20x20", marca: "porcelanite" },
    { nombre: "venecia-cobalto-20x20", marca: "porcelanite" },
    { nombre: "venecia-rosa-20x20", marca: "porcelanite" },
    { nombre: "venecia-verde-20x20", marca: "porcelanite" },
    { nombre: "venezuela-amarillo-33x33", marca: "porcelanite" },
    { nombre: "venezuela-azul-33x33", marca: "porcelanite" },
    { nombre: "venezuela-gris-33x33", marca: "porcelanite" },
    { nombre: "venezuela-rojo-33x33", marca: "porcelanite" },
    { nombre: "vetro-blanco-25x40", marca: "porcelanite" },
    { nombre: "yukon-beige-33x33", marca: "porcelanite" },
    { nombre: "yukon-cafe-33x33", marca: "porcelanite" },
    // VITROMEX
    { nombre: "alpino-oro-brillo-50x100", marca: "vitromex" },
    { nombre: "arizpe-caoba-18x60", marca: "vitromex" },
    { nombre: "arizpe-ceniza-18x60", marca: "vitromex" },
    { nombre: "arizpe-haya-18x60", marca: "vitromex" },
    { nombre: "aspen-20x30", marca: "vitromex" },
    { nombre: "azteca-azul-36x36", marca: "vitromex" },
    { nombre: "brasil-negro-mate-61x122", marca: "vitromex" },
    { nombre: "brico-multicolor-45x45", marca: "vitromex" },
    { nombre: "budapest-crema-61.2x61.2", marca: "vitromex" },
    { nombre: "budapest-gris-61.2x61.2", marca: "vitromex" },
    { nombre: "cadereyta-miel-35.7x35.7", marca: "vitromex" },
    { nombre: "cairo-azul-35.7x50.2", marca: "vitromex" },
    { nombre: "cairo-crema-35.7x50.2", marca: "vitromex" },
    { nombre: "calix-beige-37x37", marca: "vitromex" },
    { nombre: "carranza-nogal-20x60", marca: "vitromex" },
    { nombre: "carranza-rec-bianco-mate-50x100", marca: "vitromex" },
    { nombre: "castilla-terracota-37x37", marca: "vitromex" },
    { nombre: "catedral-ceniza-35.7x35.7", marca: "vitromex" },
    { nombre: "catedral-cafe-35.7x35.7", marca: "vitromex" },
    { nombre: "chapala-abedul-18x60", marca: "vitromex" },
    { nombre: "chapala-albino-18x60", marca: "vitromex" },
    { nombre: "chapala-miel-18x60", marca: "vitromex" },
    { nombre: "chapala-pino-18x60", marca: "vitromex" },
    { nombre: "cienega-multicolor-37x37", marca: "vitromex" },
    { nombre: "corfu-grafito-45x45", marca: "vitromex" },
    { nombre: "corfu-gris-45x45", marca: "vitromex" },
    { nombre: "cosala-haya-35.7x35.7", marca: "vitromex" },
    { nombre: "deco-wood-roble-37x37", marca: "vitromex" },
    { nombre: "dual-blanco-35.7x35.7", marca: "vitromex" },
    { nombre: "dual-negro-35.7x35.7", marca: "vitromex" },
    { nombre: "everest-grigio-mate-61x122", marca: "vitromex" },
    { nombre: "gaudi-oro-36x36", marca: "vitromex" },
    { nombre: "harlem-crema-62.1x62.1", marca: "vitromex" },
    { nombre: "irlanda-grafito-mate-61x122", marca: "vitromex" },
    { nombre: "jaral-miel-36x36", marca: "vitromex" },
    { nombre: "jarana-caoba-35.7x35.7", marca: "vitromex" },
    { nombre: "jarana-haya-35.7x35.7", marca: "vitromex" },
    { nombre: "linares-terracota-36x36", marca: "vitromex" },
    { nombre: "lisboa-almendra-20x20", marca: "vitromex" },
    { nombre: "lisboa-gris-20x20", marca: "vitromex" },
    { nombre: "living-beige-50x100", marca: "vitromex" },
    { nombre: "madero-moka-20x20", marca: "vitromex" },
    { nombre: "marmara-blanco-61.2x122.6", marca: "vitromex" },
    { nombre: "marmoliza-blanco-20x30", marca: "vitromex" },
    { nombre: "marmoliza-blanco-36x36", marca: "vitromex" },
    { nombre: "marmol-blanco-brillo-50x100", marca: "vitromex" },
    { nombre: "mazamitla-crema-35.7x35.7", marca: "vitromex" },
    { nombre: "mediterraneo-azul-28x60", marca: "vitromex" },
    { nombre: "mediterraneo-blanco-28x60", marca: "vitromex" },
    { nombre: "mediterraneo-verde-28x60", marca: "vitromex" },
    { nombre: "metepec-verde-20x30", marca: "vitromex" },
    { nombre: "metepec-azul-20x30", marca: "vitromex" },
    { nombre: "mila-beige-35.7x35.7", marca: "vitromex" },
    { nombre: "milpa-tierra-35.7x35.7", marca: "vitromex" },
    { nombre: "monaco-gris-20x20", marca: "vitromex" },
    { nombre: "monaco-cafe-20x20", marca: "vitromex" },
    { nombre: "monet-haya-26x100", marca: "vitromex" },
    { nombre: "napa-blanco-brillo-35.7x50.2", marca: "vitromex" },
    { nombre: "nativa-cherry-18x60", marca: "vitromex" },
    { nombre: "nexo-blanco-22x60", marca: "vitromex" },
    { nombre: "nexo-negro-22x60", marca: "vitromex" },
    { nombre: "novara-grigio-55x55", marca: "vitromex" },
    { nombre: "novara-nube-55x55", marca: "vitromex" },
    { nombre: "oslo-blanco-35.7x35.7", marca: "vitromex" },
    { nombre: "panuco-ceniza-35.7x35.7", marca: "vitromex" },
    { nombre: "papantla-azul-20x30", marca: "vitromex" },
    { nombre: "papantla-azul-35.7x35.7", marca: "vitromex" },
    { nombre: "papantla-gris-20x30", marca: "vitromex" },
    { nombre: "papantla-gris-35.7x35.7", marca: "vitromex" },
    { nombre: "peregrino-terracota-35.7x35.7", marca: "vitromex" },
    { nombre: "porto-ceniza-20x20", marca: "vitromex" },
    { nombre: "ranch-lux-castano-35.7x35.7", marca: "vitromex" },
    { nombre: "real-de-catorce-35.7x50.2", marca: "vitromex" },
    { nombre: "roma-gris-35x35", marca: "vitromex" },
    { nombre: "rubik-arena-20x20", marca: "vitromex" },
    { nombre: "rubik-azul-20x20", marca: "vitromex" },
    { nombre: "rubik-cafe-20x20", marca: "vitromex" },
    { nombre: "rubik-verde-20x20", marca: "vitromex" },
    { nombre: "sacramento-azul-37x37", marca: "vitromex" },
    { nombre: "san-gabriel-hueso-50x100", marca: "vitromex" },
    { nombre: "san-gabriel-mt-gray-50x100", marca: "vitromex" },
    { nombre: "san-joaquin-azul-20x30", marca: "vitromex" },
    { nombre: "san-joaquin-verde-20x30", marca: "vitromex" },
    { nombre: "sari-blanco-55x55", marca: "vitromex" },
    { nombre: "sena-marfil-45x45", marca: "vitromex" },
    { nombre: "sierra-cafe-35.7x35.7", marca: "vitromex" },
    { nombre: "spritz-negro-20x20", marca: "vitromex" },
    { nombre: "spritz-blanco-20x20", marca: "vitromex" },
    { nombre: "strada-terra-45x45", marca: "vitromex" },
    { nombre: "verona-grey-20x20", marca: "vitromex" },
    { nombre: "xicotepec-beige-20x30", marca: "vitromex" },
    { nombre: "xicotepec-cafe-20x30", marca: "vitromex" },
    { nombre: "xilitla-blanco-35.7x35.7", marca: "vitromex" },
    { nombre: "yukon-black-55x55", marca: "vitromex" },
    { nombre: "yukon-cream-55x55", marca: "vitromex" },
    { nombre: "zenia-iron-36x50", marca: "vitromex" },
    { nombre: "zenia-black-36x50", marca: "vitromex" }
    // DALTILE
    { nombre: "African-walnut-brown-20x90", marca: "daltile" },
    { nombre: "African-walnut-natural-20x90", marca: "daltile" },
{ nombre: "Alpha-gris-37x37", marca: "daltile" },
{ nombre: "Alpha-rojo-37x37", marca: "daltile" },
{ nombre: "Amalia-gris-30x40", marca: "daltile" },
{ nombre: "Amore-carlotta-60x60", marca: "daltile" },
{ nombre: "Amore-julieta-60x60", marca: "daltile" },
{ nombre: "Amore-stella-60x60", marca: "daltile" },
{ nombre: "Antique-wood-ocre-18x60", marca: "daltile" },
{ nombre: "Arboleda-café-45x45", marca: "daltile" },
{ nombre: "Avenza-blanco-60x1.20", marca: "daltile" },
{ nombre: "Black-walnut-moka-18x60", marca: "daltile" },
{ nombre: "Blender-stone-30x45", marca: "daltile" },
{ nombre: "Breccia-ligh-gray-60.5x60.5", marca: "daltile" },
{ nombre: "Breccia-marfil-60x60", marca: "daltile" },
{ nombre: "Cantavria-avorio-60.5x60.5", marca: "daltile" },
{ nombre: "Colonial-frida-37x37", marca: "daltile" },
{ nombre: "Corintia-oxford-60.5x60.5", marca: "daltile" },
{ nombre: "Dannes-blanco-30x45", marca: "daltile" },
{ nombre: "Dannes-café-30x45", marca: "daltile" },
{ nombre: "Dannes-gris-30x45", marca: "daltile" },
{ nombre: "Divana-brown-34x50", marca: "daltile" },
{ nombre: "Encanabanu-cerezo-18x60", marca: "daltile" },
{ nombre: "Encanabanu-natural-18x60", marca: "daltile" },
{ nombre: "Fort-wood-beige-18x60", marca: "daltile" },
{ nombre: "Fort-wood-brown-18x60", marca: "daltile" },
{ nombre: "Fort-wood-dark-gray-18x60", marca: "daltile" },
{ nombre: "Fort-wood-ligh-gray-18x60", marca: "daltile" },
{ nombre: "Glitz-blue-37x37", marca: "daltile" },
{ nombre: "Hamlet-latte-30x45", marca: "daltile" },
{ nombre: "Hamlet-motley-30x45", marca: "daltile" },
{ nombre: "Kalos-greige-45x90", marca: "daltile" },
{ nombre: "Kalos-gris-45x90", marca: "daltile" },
{ nombre: "Lake-beige-37x37", marca: "daltile" },
{ nombre: "Legend-brown-15x66", marca: "daltile" },
{ nombre: "Legend-greige-15x66", marca: "daltile" },
{ nombre: "Legend-natural-18x50", marca: "daltile" },
{ nombre: "Lucca-bianco-20x30", marca: "daltile" },
{ nombre: "Lucca-bianco-37x37", marca: "daltile" },
{ nombre: "Lumiere-blanco-37x37", marca: "daltile" },
{ nombre: "Luster-graphite-60x60", marca: "daltile" },
{ nombre: "Luster-gray-60x60", marca: "daltile" },
{ nombre: "Luster-white-37x37", marca: "daltile" },
{ nombre: "Luster-white-60.5x60.5", marca: "daltile" },
{ nombre: "Magnus-black-60x60", marca: "daltile" },
{ nombre: "Melbourne-gray-45x90", marca: "daltile" },
{ nombre: "Melbourne-multicolor-45x90", marca: "daltile" },
{ nombre: "Navia-azul-20x30", marca: "daltile" },
{ nombre: "Navia-azul-37x37", marca: "daltile" },
{ nombre: "Navia-beige-20x30", marca: "daltile" },
{ nombre: "Navia-beige-37x37", marca: "daltile" },
{ nombre: "Navida-gris-20x30", marca: "daltile" },
{ nombre: "Navia-gris-37x37", marca: "daltile" },
{ nombre: "Navia-verde-37x37", marca: "daltile" },
{ nombre: "Origin-black-rec-60x1.20", marca: "daltile" },
{ nombre: "Palatia-gold-60.5x60.5", marca: "daltile" },
{ nombre: "Patio-terraza-ocre-37x37", marca: "daltile" },
{ nombre: "Piacenza-beige-60x60", marca: "daltile" },
{ nombre: "Piacenza-gris-60x60", marca: "daltile" },
{ nombre: "Prisma-origami-blanco-30x45", marca: "daltile" },
{ nombre: "Republica-multicolor-18x60", marca: "daltile" },
{ nombre: "Rioja-multicolor-37x37", marca: "daltile" },
{ nombre: "Rockweel-gris-30x45", marca: "daltile" },
{ nombre: "Rockweel-latte-30x45", marca: "daltile" },
{ nombre: "Rockweel-multicolor-30x45", marca: "daltile" },
{ nombre: "Royal-walnut-natural-brown-15x66", marca: "daltile" },
{ nombre: "San-miguel-azul-37x37", marca: "daltile" },
{ nombre: "San-miguel-rojo-37x37", marca: "daltile" },
{ nombre: "Santa-clara-37x37", marca: "daltile" },
{ nombre: "Sayul-azul-37x37", marca: "daltile" },
{ nombre: "Segovia-latte-30x45", marca: "daltile" },
{ nombre: "Segovia-multicolor-30x45", marca: "daltile" },
{ nombre: "Sonata-black-20x90", marca: "daltile" },
{ nombre: "Sonata-gray-20x90", marca: "daltile" },
{ nombre: "Stonefort-34x50", marca: "daltile" },
{ nombre: "Stratto-black-60.5x60.5", marca: "daltile" },
{ nombre: "Stratto-gray-60.5x60.5", marca: "daltile" },
{ nombre: "Sunwood-miel-18x60", marca: "daltile" },
{ nombre: "Symbol-cotto-37x37", marca: "daltile" },
{ nombre: "Taxco-café-37x37", marca: "daltile" },
{ nombre: "Teul-beige-37x37", marca: "daltile" },
{ nombre: "Timberwood-gray-20x90", marca: "daltile" },
{ nombre: "Tula-café-37x37", marca: "daltile" },
{ nombre: "Urbania-black-30x45", marca: "daltile" },
{ nombre: "Urbania-black-white-30x45", marca: "daltile" },
{ nombre: "Urbania-blue-30x45", marca: "daltile" },
{ nombre: "Urbania-obalt-blue-30x45", marca: "daltile" },
{ nombre: "Urbania-white-30x45", marca: "daltile" },
{ nombre: "Veneto-gris-60x60", marca: "daltile" },
{ nombre: "Whisper-oak-brown-15x66", marca: "daltile" },
{ nombre: "Whisper-oak-cherry-15x66", marca: "daltile" },
{ nombre: "Whisper-oak-gray-15x66", marca: "daltile" },
{ nombre: "Zenwood-brown-45x45", marca: "daltile" }
// --- MISE ---
{ nombre: "abstrac-gold-60x1.20", marca: "mise" },
{ nombre: "alistonia-gold-60x1.20", marca: "mise" },
{ nombre: "calacatta-renoirse-60x60", marca: "mise" },
{ nombre: "castor-blue-60x1.20", marca: "mise" },
{ nombre: "cracovia-high-glossy-60x1.20", marca: "mise" },
{ nombre: "eloy-satvario-60x1.20", marca: "mise" },
{ nombre: "flicker-white-60x1.20", marca: "mise" },
{ nombre: "frize-gold-60x1.20", marca: "mise" },
{ nombre: "glassia-wood-60x1.20", marca: "mise" },
{ nombre: "iron-gold-60x1.20", marca: "mise" },
{ nombre: "lublin-60x1.20", marca: "mise" },
{ nombre: "luccano-dark-60x1.20", marca: "mise" },
{ nombre: "luccano-light-60x1.20", marca: "mise" },
{ nombre: "ollin-marble-60x1.20", marca: "mise" },
{ nombre: "onice-chiaro-glossy-60x60", marca: "mise" },
{ nombre: "onice-scuro-60x60", marca: "mise" },
{ nombre: "praga-60x1.20", marca: "mise" },
{ nombre: "roomy-black-60x1.20", marca: "mise" },
{ nombre: "stavario-ascent-grey-60x1.20", marca: "mise" },
{ nombre: "titanium-blue-60x1.20", marca: "mise" }
{ nombre: "titanium-blue-60x60", marca: "mise" }
// --- BENADRESA ---
{ nombre: "avenue-beige-30x90", marca: "benadresa" },
{ nombre: "blanco-brillo-30x90", marca: "benadresa" },
{ nombre: "cascais-30x90", marca: "benadresa" },
{ nombre: "decor-dune-newbury-white-30x60", marca: "benadresa" },
{ nombre: "gothel-cream-30x60", marca: "benadresa" },
{ nombre: "gothel-moka-30x90", marca: "benadresa" },
{ nombre: "keid-gothel-cream-30x90", marca: "benadresa" },
{ nombre: "keid-gothel-moka-30x90", marca: "benadresa" },
{ nombre: "leaves-avenue-beige-30x90", marca: "benadresa" },
{ nombre: "leaves-blanco-brillo-30x90", marca: "benadresa" },
{ nombre: "leaves-cascais-30x90", marca: "benadresa" },
{ nombre: "leaves-stryn-30x90", marca: "benadresa" },
{ nombre: "newbury-white-30x60", marca: "benadresa" },
{ nombre: "stryn-30x90", marca: "benadresa" }
];

// --- 3. MOTOR DE PROYECCIÓN (8 PUNTOS) ---
function renderizarTextura() {
    const canvasId = (modoEdicion === 'piso') ? 'floor-canvas' : 'wall-canvas';
    const canvas = document.getElementById(canvasId);
    if (!canvas || !texturaActual) return;

    const ctx = canvas.getContext('2d');
    const img = new Image();
    img.src = texturaActual;

    img.onload = () => {
        // IDs según el modo activo: p1-p4 para piso, p5-p8 para figura/muro
        const IDs = (modoEdicion === 'piso') ? ['p1', 'p2', 'p3', 'p4'] : ['p5', 'p6', 'p7', 'p8'];
        
        const pts = IDs.map(id => {
            const el = document.getElementById(id);
            if (!el) return { x: 0, y: 0 };
            return { x: el.offsetLeft, y: el.offsetTop };
        });

        const viewport = document.getElementById('viewport');
        canvas.width = viewport.clientWidth;
        canvas.height = viewport.clientHeight;

        const srcPts = [0, 0, img.width, 0, img.width, img.height, 0, img.height];
        const dstPts = [pts[0].x, pts[0].y, pts[1].x, pts[1].y, pts[2].x, pts[2].y, pts[3].x, pts[3].y];
        
        try {
            const transform = PerspectiveTransform(srcPts, dstPts);
            ctx.clearRect(0, 0, canvas.width, canvas.height);
            canvas.style.transform = transform.getCSS();
            canvas.style.transformOrigin = "0 0";
            canvas.style.mixBlendMode = "multiply"; 
            ctx.drawImage(img, 0, 0, img.width, img.height);
        } catch (e) {
            console.error("Error en PerspectiveTransform:", e);
        }
    };
}

// --- 4. FUNCIONES DE INTERFAZ ---
function setModo(modo) {
    modoEdicion = modo;
    console.log("Modo activo: " + modoEdicion);
}

function cambiarHabitacion(archivo) {
    const bg = document.getElementById('bg-room');
    if (bg) bg.src = 'img/habitaciones/' + archivo;
}

function mostrarProductos(marca) {
    const contenedor = document.getElementById('catalog-container');
    if (!contenedor) return;
    contenedor.innerHTML = ''; 

    const filtrados = misProductos.filter(p => marca === 'todas' || p.marca === marca);

    filtrados.forEach(producto => {
        const card = document.createElement('div');
        card.className = 'tile-card';
        const ruta = `img/ceramicas/${producto.nombre}.jpg`;

        card.innerHTML = `
            <img src="${ruta}" style="width:100%; cursor:pointer;" onerror="this.src='img/error.jpg'">
            <p style="color:white; font-size:10px; margin-top:5px;">${producto.nombre}</p>
        `;

        card.onclick = () => {
            texturaActual = ruta;
            renderizarTextura();
        };
        contenedor.appendChild(card);
    });
}

// --- 5. ARRASTRE DE PUNTOS ---
document.querySelectorAll('.dot').forEach(dot => {
    dot.onmousedown = function(e) {
        document.onmousemove = function(ev) {
            const viewport = document.getElementById('viewport');
            let x = ev.pageX - viewport.offsetLeft;
            let y = ev.pageY - viewport.offsetTop;
            
            dot.style.left = x + 'px';
            dot.style.top = y + 'px';
            
            renderizarTextura(); 
        };
        document.onmouseup = function() {
            document.onmousemove = null;
        };
    };
});

// Carga inicial
window.onload = () => {
    mostrarProductos('todas');
};
